name: Prueba mínima

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hola Mundo
        run: echo "Hola desde GitHub Actions"
